[package]
name = "storefront"
version = "0.1.0"
edition = "2021"
authors = ["Nathaniel Colin Tabacchi<tabacchn@mail.gvsu.edu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
